config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions:'users/sessions', registrations: 'users/registrations',
                                   passwords:'users/passwords', confirmations: 'users/confirmations'}
  devise_scope :user do
    get '/user/sign_out', to: 'users/sessions#destroy'
    get '/users/:id/bookings', to: 'users#bookings', as: 'user_bookings'
    get '/users/:id/manage_booking_delete', to: 'journeys#manage_booking_delete', as: 'user_manage_booking_delete'
    get '/users/:id/manage_booking_update', to: 'journeys#manage_booking_update', as: 'user_manage_booking_update'
    get '/users/:id/bookings/detail', to: 'users#detail_booking', as: 'user_detail_booking'
  end
  resources :journeys, only: [:create, :destroy, :new]
  resources :drivers, only: [:new, :edit, :create, :update, :destroy] do
    get 'confirm_destroy', to: 'drivers#confirm_destroy', as: 'confirm_destroy'
    resources :vehicles
    resources :routes
    resources :journeys, only: [:index]
    resources :stages, only: :update
  end
  resources :stages, only: [:create, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messagges, only: [:index, :create]
  end
  resources :ratings, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new, :destroy]
  resources :users, only: [:show] do
    resources :pay_methods
  end
  resources :searches
  resources :routes, only: [] do
    get 'detail', action: 'detail', on: :collection
    resources :journeys, only: [:edit, :update] do
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get "/404", :to => "errors#not_found"
  get "/442", :to => "errors#record_not_found"
  get "/500", :to => "errors#internal_server_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/users/:id/pay_methods/', to: 'pay_method#index',  as: 'user_pay_methods_index'
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :user, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :target, polymorphic: true
  belongs_to :second_target, polymorphic: true

  scope :unread, ->{ where(read_at: nil)}

  # crea le notifiche per i driver delle route prenotate
  def self.create_notifications_td(driver_id, actor, target, second_target, notify_type)
    user = User.where(driver_id: driver_id).first
    Notification.create! do |notification|
      notification.user = user
      notification.actor = actor
      notification.target = target
      notification.second_target = second_target
      notification.notify_type = notify_type
    end
  end

  # crea le notifiche per gli autostoppisti
  def self.create_notifications_th(user_id, actor, target, second_target, notify_type)
    user = User.find(user_id)
    Notification.create! do |notification|
      notification.user = user
      notification.actor = actor
      notification.target = target
      notification.second_target = second_target
      notification.notify_type = notify_type
    end
  end


end

app/controllers/notifications_controller.rb
  class NotificationsController < ApplicationController
    def index
      @notifications = Notification.where(user: current_user).unread.select {|x| deleted_target?(x)}
    end

    # POST
    def mark_as_read
      @notifications = Notification.where(user: current_user, id: params[:id]).unread
      @notifications.update_all(read_at: Time.zone.now)
      render json: {success: true}
    end

    def clean
      notifications.delete_all
      redirect_to notifications_path
    end

    private

    def notifications
      raise 'You need reqiure user login for /notifications page.' unless current_user
      Notification.where(user_id: current_user.id)
    end

    def deleted_target? (obj)
      obj.target != nil && obj.second_target != nil
    end
  end

app/views/notifications/_accept_trip.html.erb
<!-- se viene accettata la tratta dal driver, si manda l'utente al dettaglio della prenotazione-->
<div>
  <%= link_to user_bookings_path(notification.user), :'data-behavior' => "notifications-link", id: "#{notification.id}", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha accettato di viaggiare con te sulla tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %>
    <br>
  <% end %>
</div>

app/views/notifications/_cancel.html.erb
<!-- notifica per il driver mandata quando l'autostoppista annulla la prenotazione. Il driver viene mandato sulla pagina della tratta, così
vede gli utenti prenotati-->
<div>
  <%= link_to driver_route_path(notification.user, notification.target.id), :'data-behavior' => "notifications-link", id: "#{notification.id}",class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha annullato la prenotazione alla tua tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %> !
    <br>
  <% end %>
</div>

app/views/notifications/_delete_multitrip.html.erb
<!-- Se viene cancellata una route che faceva parte del multiviaggio prenotato
il path di manage booking è da cambiare come segue perchè non passo più il journey id,
quindi gli passo l'id della route cancellata e l'id dell'altra route del multiviaggio-->
<div>
  <%= link_to user_manage_booking_delete_path(notification.user,target: notification.target.id, other: notification.second_target.id), :'data-behavior' => "notifications-link", id: "#{notification.id}", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha cancellato la tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %>
    <br>
  <% end %>
</div>
<!--NB: Se entrambi gli autostoppisti cancellano le route, il manage_booking non può chiedergli di mantenere l'altra tratta visto che è stata cancellata,
bisogna fare un controllo in modo che se entrambe le tratte sono cancellate, lo avvisi e lo mandi direttamente alla ricerca complessiva (dato che non ha
altre scelte -->

app/views/notifications/_delete_trip.html.erb
<div>
  <%= link_to new_search_path(c_part: notification.target.citta_partenza,c_arr: notification.target.citta_arrivo, data_ora: notification.target.data_ora_partenza), :'data-behavior' => "notifications-link", id: "#{notification.id}" , class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha cancellato la tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %>
    <br>
  <% end %>
</div>

app/views/notifications/_reject_trip.html.erb
<!-- se viene rifiutata la tratta dal driver, si manda l'utente alla ricerca e si arrangia, perchè se è stato rifiutato vuol dire che è
una brutta persona e se lo merita-->
<div>
  <%= link_to new_search_path(c_part: notification.target.citta_partenza,c_arr: notification.target.citta_arrivo,data_ora: notification.target.data_ora_partenza), :'data-behavior' => "notifications-link", id: "#{notification.id}", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%=notification.actor.username %> non ha accettato di viaggiare con te sulla tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %> !
    <br>
  <% end %>
</div>

app/views/notifications/_reservation.html.erb
<!--manda il driver sulla pagina di gestione della richiesta il target è la route e il second target è la journey-->
<div>
  <%= link_to edit_route_journey_path(notification.target.id, notification.second_target), :'data-behavior' => "notifications-link", id: "#{notification.id}", name: "notification", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <span class='indent-1'></span>
    <%=notification.actor.username%> vuole partecipare alla tua tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %> !
    <br>
  <% end %>
</div>

app/views/notifications/_update_multitrip.html.erb
<!-- Se viene modificata una route che faceva parte del multiviaggio prenotato
il path di manage booking è da cambiare come segue perchè non passo più il journey id,
quindi gli passo l'id della route modificata e l'id dell'altra route del multiviaggio-->
<div>
  <%= link_to user_manage_booking_update_path(notification.user,target: notification.target.id, other: notification.second_target.id), :'data-behavior' => "notifications-link", id: "#{notification.id}", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha modificato la tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %>
    <br/>
  <% end %>
</div>
<!--NB: Se entrambi gli autostoppisti modificano le route o una modifica rende impossibile il cambio, il manage_booking dovrebbe dargli
la possibilità di scegliere quale delle due tratte cancellare eventualmente (oltre a cancellarle entrambe e ricercarle)-->

app/views/notifications/_update_trip.html.erb
<!-- se viene modificata la tratta singola che è stata prenotata, si manda l'utente al dettaglio della prenotazione, poi si arrangia lui nel
caso ad annullare la prenotazione e a ricercare-->
<div>
  <%= link_to user_bookings_path(notification.user, notification.target.id), :'data-behavior' => "notifications-link", id: "#{notification.id}", class: "mobile-notif depth-1 dropdown-item #{"unread" if !notification.read_at?}" do %>
    <%= notification.actor.username %> ha modificato la tratta <%= notification.target.citta_partenza %> - <%= notification.target.citta_arrivo %>
    <br/>
  <% end %>
</div>