config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions:'users/sessions', registrations: 'users/registrations',
                                   passwords:'users/passwords', confirmations: 'users/confirmations'}
  devise_scope :user do
    get '/user/sign_out', to: 'users/sessions#destroy'
    get '/users/:id/bookings', to: 'users#bookings', as: 'user_bookings'
    get '/users/:id/manage_booking_delete', to: 'journeys#manage_booking_delete', as: 'user_manage_booking_delete'
    get '/users/:id/manage_booking_update', to: 'journeys#manage_booking_update', as: 'user_manage_booking_update'
    get '/users/:id/bookings/detail', to: 'users#detail_booking', as: 'user_detail_booking'
  end
  resources :journeys, only: [:create, :destroy, :new]
  resources :drivers, only: [:new, :edit, :create, :update, :destroy] do
    get 'confirm_destroy', to: 'drivers#confirm_destroy', as: 'confirm_destroy'
    resources :vehicles
    resources :routes
    resources :journeys, only: [:index]
    resources :stages, only: :update
  end
  resources :stages, only: [:create, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messagges, only: [:index, :create]
  end
  resources :ratings, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new, :destroy]
  resources :users, only: [:show] do
    resources :pay_methods
  end
  resources :searches
  resources :routes, only: [] do
    get 'detail', action: 'detail', on: :collection
    resources :journeys, only: [:edit, :update] do
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get "/404", :to => "errors#not_found"
  get "/442", :to => "errors#record_not_found"
  get "/500", :to => "errors#internal_server_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/users/:id/pay_methods/', to: 'pay_method#index',  as: 'user_pay_methods_index'
end

app/models/user.rb
require 'carrierwave/orm/activerecord'

class UserValidator < ActiveModel::Validator
  def validate(record)
    if record.data_di_nascita.blank?
      record.errors[:data_di_nascita] << "campo obbligatorio?!"
    elsif record.data_di_nascita > 18.years.ago
      record.errors[:data_di_nascita] << "non accettabile (scusa, ma devi avere almeno 18 anni per iscriverti)"
    end
  end
end

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  validates_with UserValidator

  mount_uploader :avatar, AvatarUploader

  # Trova tutti i rating associati al driver e ne fa la media
  def find_rating_driver
    Review.where("driver_id = ?", self.driver_id).average(:vote)
  end

  # Trova tutti i rating dell'autospottista e ne fa la media
  def find_rating_autostoppista
    Rating.where("user_id = ?", self.id).average(:vote)
  end

  # Recupero tutte le tratte singole prenotate dall'utente
  def find_bookings(user_id)
    Journey.includes(:stages, :routes).where(user_id:user_id, stages:{accepted:true})
        .or(Journey.includes(:stages, :routes).where(user_id:user_id, stages:{accepted:nil}))
        .order(data_ora_partenza: 'ASC')
  end

  # @author serva
  #
  # @note controlla se il guidatore e l'autostoppista hanno viaggiato insieme in precedenza
  # @note questo per permettere di valutare solo dopo aver viaggiato insieme almeno una volta
  # @note (valido sia per rating che per review)
  #
  # @note spostata in user perché uguale sia in review.rb che rating.rb
  #
  # @param [Numeric] user_id
  # @param [Numeric] driver_id
  #
  # @return [TrueClass, FalseClass]
  def self.has_previous_journey_done(user_id, driver_id)
    journeys = Stage.joins(:journey, :route).where('journeys.user_id = ? and routes.driver_id=?', user_id, driver_id).order('routes.data_ora_arrivo')
    if journeys.present?
      journeys.each do |j|
        if j.route.data_ora_arrivo.utc < DateTime.now.utc
          return true
        end
      end
      return false
    end
  end

  belongs_to :driver, optional: true, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :pay_methods, inverse_of: :user, dependent: :destroy
  has_many :messagges
  has_many :journeys, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :notifications, foreign_key: :user_id
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.avatar = params[:avatar]
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :cognome, :username, :data_di_nascita, :cellulare,
                                                       :indirizzo, :avatar, :deleted])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :cognome, :username, :data_di_nascita, :cellulare,
                                                              :indirizzo, :current_password, :avatar])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # mostro la pagina dell'utente
  # GET /users/1
  # GET /users/1.json
  def show
      @user = User.find(params[:id])
  end

  # mostro tutte le route prenotate dall'utente loggato
  # GET /users/1/bookings
  def bookings
    @user=User.find(current_user.id)
    journeys=@user.find_bookings(current_user.id)
    #distinguo tra tratte ancora attive e tratte passate
    @journeys_active =[]
    @journeys_past = []
    journeys.each do |journey|
      unless journey.stages.first.accepted == false
        if journey.stages.first.route.data_ora_partenza >= Time.now
          @journeys_active << journey
        else
          @journeys_past << journey
        end
      end
    end
  end

  # mostro dettagli della tratta prenotata
  # GET /users/:id/bookings/detail
  def detail_booking
    begin
      @journey = Journey.find(params[:j_id])
      @routes = []
      @ute_drivers = []
      @journey_ok = (@journey.user_id == current_user.id)
      @journey.stages.each do |stage|
        @routes << stage.route
        @ute_drivers << stage.route.driver.user
      end
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "#{1.year.ago}"
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :username, :password, :nome, :cognome, :data_di_nascita, :cellulare, :indirizzo, :url_foto, :deleted)
  end
end

app/views/users/_detail_route.html.erb
<div class="col-12 col-12-mobilep">
  <h4 class="col-4 col-12-narrower">
    <strong>Citta partenza:</strong>
    <%= route.citta_partenza %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Luogo ritrovo:</strong>
    <%= route.luogo_ritrovo %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Data ora partenza:</strong>
    <%= route.data_ora_partenza.strftime("il %d-%m-%Y alle %H:%M:%S") %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Citta arrivo:</strong>
    <%= route.citta_arrivo %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Data ora arrivo:</strong>
    <%= route.data_ora_arrivo.strftime("il %d-%m-%Y alle %H:%M:%S") %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Costo:</strong>
    <%= route.costo %>
  </h4>

  <h4 class="col-4 col-12-narrower">
    <strong>Tempo di percorrenza:</strong>
    <%= route.tempo_percorrenza %>
  </h4>

  <h4 class="col-4 col-12-narrower">
    <strong>Posti prenotati</strong>
    <%= route.n_passeggeri %>
  </h4>
  <!-- link per la pagina del driver-->
  <h4 class="col-4 col-12-narrower">
    <strong>Driver:</strong>
    <%=link_to driver.nome + driver.cognome, user_path(id:driver.id)%>
  </h4>
</div>
<!-- passaggio alla chat con il driver-->
<div class="col-12 col-12-mobilep"><br></div>
<%= form_with(model: Chat, local: true, method: "post") do |form| %>
  <%= form.hidden_field :user_2_id, :value => driver.id %>
  <div class="col-12 col-12-mobilep">
    <%= form.submit "Chatta con " + driver.nome%>
  </div>
<%end%>

app/views/users/bookings.html.erb
<!-- Pagina di visualizzazione delle tratte prenotate da utente loggato-->
<!-- controllo che l'utente passato nella url sia quello corrente-->
<%if @user.id==current_user.id %>
  <!--se non ho tratte attive visualizzo messaggio-->
  <%if @journeys_active.empty?%>
    <%unless @journeys_past.empty? %>
      <h4 class="col-12 col-12-narrower"> NON HAI NESSUNA TRATTA ATTIVA PRENOTATA!</h4>
    <%end %>
  <%else %>
    <!-- visualizzo le tratte attive-->
    <div class="col-12 col-12-mobilep" style="overflow: auto;">
      <table>
        <caption><h3><strong>Prenotazioni Attive</strong></h3></caption>
        <% if notice %>
          <h2 class="error"><%= notice %></h2>
        <% end %>
        <thead>
        <tr>
          <th>Città di Partenza</th>
          <th>Luogo di ritrovo</th>
          <th>Data e ora partenza</th>
          <th>Città di arrivo</th>
          <th>Data e ora arrivo</th>
          <th>Costo</th>
          <th>Accettato</th>
          <th>Pagato</th>
        </tr>
        </thead>
        <tbody>
        <%@journeys_active.each do |journey| %>
          <%journey.stages.sort_by { |x | x.route.data_ora_partenza  }.each do |stage| %>
            <tr>
              <td><%= stage.route.citta_partenza %></td>
              <td><%= stage.route.luogo_ritrovo %></td>
              <td><%= stage.route.data_ora_partenza.strftime("%d/%m/%y, %H:%M") %></td>
              <td><%= stage.route.citta_arrivo %></td>
              <td><%= stage.route.data_ora_arrivo.strftime("%d/%m/%y, %H:%M") %></td>
              <td><%= stage.route.costo %></td>
              <%if stage.accepted == nil %>
                <td>
                  <input type="checkbox" name="accettato" value="true" disabled="disabled">
                  <label for="accettato"></label>
                </td>
              <%elsif stage.accepted %>
                <td>
                  <input type="checkbox" name="accettato" value="true" checked="checked" disabled="disabled">
                  <label for="accettato"></label>
                </td>
              <%end %>
              <%if journey.pay_method_id==nil || journey.pay_method_id==0%>
                <td>
                  <input type="checkbox" name="pagato" value="true" disabled="disabled">
                  <label for="pagato"></label>
                </td>
              <%else %>
                <td>
                  <input type="checkbox" name="pagato" checked="checked" disabled="disabled">
                  <label for="pagato"></label>
                </td>
              <%end %>
                <td><%= link_to 'Dettagli', user_detail_booking_path(j_id:journey.id), class: "button" %></td>
            </tr>
          <%end %>
          <!-- inserisco riga vuota per separare le eventuali prenotazioni multitratta-->
          <tr><td colspan="9"></td></tr>
        <%end %>
        </tbody>
      </table>
    </div>
    <div class="col-12 col-12-mobilep"><hr></div>
  <%end %>
  <!-- visualizzo le tratte passate -->
  <%if @journeys_past.empty? && @journeys_active.empty?%>
    <h4 class="col-5 col-12-narrower">Non hai mai prenotato una tratta!</h4>
  <%elsif !@journeys_past.empty? %>
    <div class="col-12 col-12-mobilep" style="overflow: auto;">
      <table>
        <caption><h3><strong>Prenotazioni Passate</strong></h3></caption>
        <thead>
        <tr>
          <th>Città di Partenza</th>
          <th>Luogo di ritrovo</th>
          <th>Data e ora partenza</th>
          <th>Città di arrivo</th>
          <th>Data e ora arrivo</th>
          <th>Costo</th>
          <th colspan="1"></th>
        </tr>
        </thead>
        <tbody>
        <% @journeys_past.each do |journey|  %>
          <% journey.stages.each do |stage|  %>
            <tr>
              <td><%=  stage.route.citta_partenza  %></td>
              <td><%=  stage.route.luogo_ritrovo  %></td>
              <td><%=  stage.route.data_ora_partenza.strftime("%d/%m/%y, %H:%M")  %></td>
              <td><%=  stage.route.citta_arrivo  %></td>
              <td><%=  stage.route.data_ora_arrivo.strftime("%d/%m/%y, %H:%M")  %></td>
              <td><%=  stage.route.costo  %></td>
              <td><%=  link_to 'Dettagli', user_detail_booking_path(j_id:journey.id), class: "button" %></td>
            </tr>
          <% end  %>
          <tr>
            <td colspan="7"></td>
          </tr>
        <% end  %>
        </tbody>
      </table>
    </div>
    <div class="col-12 col-12-mobilep"><br></div>
  <%end%>
  <div class="col-7 col-0-mobilep"></div>
  <div class="col-3 col-12-mobilep">
    <%= link_to 'Cerca nuove tratte!', new_search_path, class:"button" %>
  </div>
<%else %>
  <div class="col-7 col-12-mobilep">
    <h4>Non puoi vedere le prenotazioni di questo utente!</h4>
  </div>
  <div class="col-3 col-12-mobilep">
    <%= link_to 'Le tue prenotazioni!', user_bookings_path(current_user.id), class:'button'%>
  </div>
<% end %>
<div class="col-2 col-12-mobilep">
  <%= link_to 'Back', root_path, class:"button special" %>
</div>

app/views/users/detail_booking.html.erb
<!-- Pagina dei dettagli della route prenotata -->
<div class="col-2 col-4-mobilep ">
  <%= link_to 'Back', user_bookings_path, class: "button icon solid fa-chevron-left"%>
</div>
<% if @journey_ok %>
  <!-- dettagli della route-->
  <div class="col-10 col-8-mobilep">
    <h2>La tua prenotazione</h2>
  </div>
  <div class="col-12 col-12-mobilep">
    <br>
    <% if notice %>
      <h2 class="error"><%= notice %></h2>
    <% end %>
  </div>
  <% @routes.each_with_index do | route , index | %>
    <div class="col-5 col-12-mobilep">
      <%= render 'detail_route', route: route, driver: @ute_drivers[index] %>
      <%if @routes.length > 1 && route.data_ora_partenza > DateTime.current%>
        <%= link_to 'Annulla prenotazione', stage_path(j_id: params[:j_id], r_id: route.id), method: :delete, data: { confirm: 'Sicuro di voler annullare questa prenotazione?' }, class: "button special" ,title: 'Annulla prenotazione'%>
      <%end %>
    </div>
  <%end%>
  <%if @routes.first.data_ora_partenza > DateTime.current%>
    <div class="col-12 col-12-mobile"><br></div>
    <div class="col-12 col-12-mobile">
      <%= link_to 'Annulla il viaggio', journey_path(id: @journey.id),method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione?' }, class: "button special" ,title: 'Cerca nuovo viaggio' %>
    </div>
  <%end %>
<%else %>
  <div class="col-10 col-8-mobilep">
    <h2>Questa non è la tua prenotazione!</h2>
  </div>
<%end %>

app/views/users/show.html.erb
<!--Pagina profilo utente-->
<div class="row gtr-uniform">
  <h4 class="image col-12 col-12-narrower">
    <%if @user.avatar.url == nil%>
      <%= image_tag 'images/default.jpeg' , size: "160"%>
    <%else %>
      <%=image_tag(@user.avatar.url, size: "160") %>
    <%end %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Nome:</strong>
    <%= @user.nome %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Cognome:</strong>
    <%= @user.cognome %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Username:</strong>
    <%= @user.username %>
  </h4>
  <!-- Dati che visualizzo solo se sono il proprietario del profilo -->
  <%if current_user.id == @user.id %>
    <h4 class="col-4 col-12-narrower">
      <strong>Email:</strong>
      <%= @user.email %>
    </h4>
    <h4 class="col-4 col-12-narrower">
      <strong>Data di nascita:</strong>
      <%= @user.data_di_nascita %>
    </h4>
    <h4 class="col-4 col-12-narrower">
      <strong>Cellulare:</strong>
      <%= @user.cellulare %>
    </h4>
    <h4 class="col-4 col-12-narrower">
      <strong>Indirizzo:</strong>
      <%= @user.indirizzo %>
    </h4>
    <h4 class="col-8 col-12-mobilep">
      <strong><%= link_to 'Visualizza i tuoi metodi di pagamento', user_pay_methods_path(@user)%></strong>
    </h4>
  <%end %>
  <hr class="col-12 col-12-mobilep">
  <div class="col-6 col-12-narrower">
    <h4><strong>Rating medio autostoppista</strong></h4>
    <%if @user.hitch_hiker_rating==nil %>
      Nessuna valutazione presente!
    <%else %>
      <%=@user.hitch_hiker_rating.round(2)%>
    <%end %>
  </div>

  <div class="col-6 col-12-narrower">
    <%= link_to 'Guarda i voti di ' + @user.nome + ' da autostoppista', ratings_path(user_id: @user.id), class:'button' %>
  </div>
  <!-- Se sono un driver visualizzo il mio rating-->
  <%if @user.driver_id? %>
    <div class="col-6 col-12-narrower">
      <h4><strong>Rating medio Automobilista</strong></h4>
      <%ratingDriver= @user.find_rating_driver%>
      <%if ratingDriver==nil %>
        Nessuna valutazione presente!
      <%else %>
        <%=ratingDriver.round(2)%>
      <%end %>
    </div>

    <div class="col-6 col-12-narrower">
      <%= link_to 'Guarda le recensioni di ' + @user.nome + ' da guidatore', reviews_path(user_id: @user.id), class:'button' %>
    </div>

  <%end%>
</div>
<hr class="col-12 col-12-mobilep">
<!-- Visualizzazione profilo di un altro utente -->
<%if @user.id == current_user.id %>
  <div class="col-7 col-0-mobilep"></div>
  <div class="col-2 col-12-mobilep">
    <%= link_to 'Edit', edit_user_registration_path , class:'button'%>
  </div>
  <div class="col-3 col-12-mobilep">
    <%= link_to 'Back', :back, class:'button special' %>
  </div>
<%else %>
  <div class="col-7 col-0-mobilep"></div>
  <div class="col-2 col-0-mobilep"></div>
  <div class="col-3 col-12-mobilep">
    <%= link_to 'Back', root_path, class:'button special' %>
  </div>
<%end %>