config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions:'users/sessions', registrations: 'users/registrations',
                                   passwords:'users/passwords', confirmations: 'users/confirmations'}
  devise_scope :user do
    get '/user/sign_out', to: 'users/sessions#destroy'
    get '/users/:id/bookings', to: 'users#bookings', as: 'user_bookings'
    get '/users/:id/manage_booking_delete', to: 'journeys#manage_booking_delete', as: 'user_manage_booking_delete'
    get '/users/:id/manage_booking_update', to: 'journeys#manage_booking_update', as: 'user_manage_booking_update'
    get '/users/:id/bookings/detail', to: 'users#detail_booking', as: 'user_detail_booking'
  end
  resources :journeys, only: [:create, :destroy, :new]
  resources :drivers, only: [:new, :edit, :create, :update, :destroy] do
    get 'confirm_destroy', to: 'drivers#confirm_destroy', as: 'confirm_destroy'
    resources :vehicles
    resources :routes
    resources :journeys, only: [:index]
    resources :stages, only: :update
  end
  resources :stages, only: [:create, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messagges, only: [:index, :create]
  end
  resources :ratings, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new, :destroy]
  resources :users, only: [:show] do
    resources :pay_methods
  end
  resources :searches
  resources :routes, only: [] do
    get 'detail', action: 'detail', on: :collection
    resources :journeys, only: [:edit, :update] do
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get "/404", :to => "errors#not_found"
  get "/442", :to => "errors#record_not_found"
  get "/500", :to => "errors#internal_server_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/users/:id/pay_methods/', to: 'pay_method#index',  as: 'user_pay_methods_index'
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	validates :targa, presence: true, uniqueness: true
	validates :posti, presence: true, numericality: {greater_than: 0, less_than: 9, only_integer: true}
	validates :comfort, presence: true, numericality: {greater_than: 0, less_than_or_equal_to: 10, only_integer: true}
	
	has_many :routes, dependent: :destroy
	belongs_to :driver

	TIPI = ['Altro','Berlina', 'Cabriolet', 'Camper', 'Coupé', 'Fuoristrada', 'Monovolume', 'Pick up', 'Pulmino', 'Roadster', 'Station wagon', 'SUV']

	#estrai il numero di posti
	scope :max_passengers, -> (vehicle_id)  do
		select('posti').where('id = ?', vehicle_id).first.posti
	end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :get_driver
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = @driver.vehicles.order(targa: :asc)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = @driver.vehicles.build
    session[:return_to] ||= request.referer
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = @driver.vehicles.build(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to  driver_vehicles_path(@driver), notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to driver_vehicles_path(@driver), notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to driver_vehicles_path(@driver), notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = @driver.vehicles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:driver_id, :targa, :marca, :modello, :immatricolazione, :comfort, :posti, :deleted,:tipo_mezzo)
    end

    def get_driver
      @driver = Driver.find(current_user.driver_id)
    end
end

app/views/vehicles/_form.html.erb
<%= form_with model: [@driver, vehicle], local: true, html: {class: "row col-12 col-12-mobilep"} do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation" class="col-12 col-12-mobilep">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-4 col-12-mobilep">
    <%= form.label :targa %>
    <%= form.text_field :targa %>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label :marca %>
    <%= form.text_field :marca %>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label :modello %>
    <%= form.text_field :modello %>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label :tipo_mezzo, 'Tipo di mezzo' %>
    <%= form.collection_select :tipo_mezzo, Vehicle::TIPI, :to_s, :to_s %>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label :immatricolazione %>
    <%= form.text_field :immatricolazione, onfocus: "(this.type='date')" %>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label "Comfort - da 1 a 10" %>
    <%= form.number_field :comfort, min: 1, max: 10%>
  </div>

  <div class="col-4 col-12-mobilep">
    <%= form.label "Posti disponibili (oltre il tuo) - da 1 a 8" %>
    <%= form.number_field :posti, min: 1, max: 8 %>
  </div>

  <hr class="col-12 col-12-mobilep">

  <div class="col-4 col-12-mobilep">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h2>Modifica i dettagli del veicolo</h2>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Mostra', [@driver, @vehicle] %> |
<%= link_to 'Indietro', driver_vehicles_path(@driver) %>

app/views/vehicles/index.html.erb
<div class="col-12 col-12-narrower">
  <h2>
    <strong>Ecco i tuoi veicoli!</strong>
  </h2>
</div>

<table>
  <thead>
  <tr>
    <th>Targa</th>
    <th>Marca</th>
    <th>Modello</th>
    <th>Tipo di mezzo</th>
    <th>Immatricolazione</th>
    <th>Comfort</th>
    <th>Posti</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @vehicles.each do |vehicle| %>
    <tr>
      <td><%= vehicle.targa %></td>
      <td><%= vehicle.marca %></td>
      <td><%= vehicle.modello %></td>
      <td><%= vehicle.tipo_mezzo %></td>
      <% unless vehicle.immatricolazione.nil?%>
        <td><%= vehicle.immatricolazione.strftime("%d/%m/%y") %></td>
      <%end %>
      <td><%= vehicle.comfort %></td>
      <td><%= vehicle.posti %></td>
      <td><%= link_to 'Dettagli', driver_vehicle_path(@driver, vehicle) %></td>
      <td><%= link_to 'Modifica', edit_driver_vehicle_path(@driver, vehicle) %></td>
      <td><%= link_to 'Elimina', [@driver, vehicle], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi un veicolo', new_driver_vehicle_path %>
<%= link_to 'Back', user_path(current_user) %>

app/views/vehicles/new.html.erb
<h2>Nuovo Veicolo</h2>


<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Indietro', :back %>

app/views/vehicles/show.html.erb
<p>
  <strong>Targa:</strong>
  <%= @vehicle.targa %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @vehicle.marca %>
</p>

<p>
  <strong>Modello:</strong>
  <%= @vehicle.modello %>
</p>

<p>
  <strong>Tipo di mezzo:</strong>
  <%= @vehicle.tipo_mezzo %>
</p>

<p>
  <strong>Immatricolazione:</strong>
  <%= @vehicle.immatricolazione %>
</p>

<p>
  <strong>Comfort:</strong>
  <%= @vehicle.comfort %>
</p>

<p>
  <strong>Posti:</strong>
  <%= @vehicle.posti %>
</p>


<%= link_to 'Modifica', edit_driver_vehicle_path(@driver, @vehicle) %> |
<%= link_to 'Indietro', driver_vehicles_path(@driver) %>