config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions:'users/sessions', registrations: 'users/registrations',
                                   passwords:'users/passwords', confirmations: 'users/confirmations'}
  devise_scope :user do
    get '/user/sign_out', to: 'users/sessions#destroy'
    get '/users/:id/bookings', to: 'users#bookings', as: 'user_bookings'
    get '/users/:id/manage_booking_delete', to: 'journeys#manage_booking_delete', as: 'user_manage_booking_delete'
    get '/users/:id/manage_booking_update', to: 'journeys#manage_booking_update', as: 'user_manage_booking_update'
    get '/users/:id/bookings/detail', to: 'users#detail_booking', as: 'user_detail_booking'
  end
  resources :journeys, only: [:create, :destroy, :new]
  resources :drivers, only: [:new, :edit, :create, :update, :destroy] do
    get 'confirm_destroy', to: 'drivers#confirm_destroy', as: 'confirm_destroy'
    resources :vehicles
    resources :routes
    resources :journeys, only: [:index]
    resources :stages, only: :update
  end
  resources :stages, only: [:create, :destroy]
  resources :chats, only: [:index, :create, :destroy] do
    resources :messagges, only: [:index, :create]
  end
  resources :ratings, only: [:index, :create, :new]
  resources :reviews, only: [:index, :create, :new, :destroy]
  resources :users, only: [:show] do
    resources :pay_methods
  end
  resources :searches
  resources :routes, only: [] do
    get 'detail', action: 'detail', on: :collection
    resources :journeys, only: [:edit, :update] do
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get "/404", :to => "errors#not_found"
  get "/442", :to => "errors#record_not_found"
  get "/500", :to => "errors#internal_server_error"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/users/:id/pay_methods/', to: 'pay_method#index',  as: 'user_pay_methods_index'
end

app/models/journey.rb
class JourneyUSValidator < ActiveModel::Validator
	def validate(record)
		if record.user_id.blank?
			record.errors[:user_id] << "Non può essere nil"
			# non si possono prenotare tratte
		elsif Route.booked(record.stages.first.route_id ,record.user_id).exists?
			record.errors[:user_id] << "Tratta già prenotata"
		end
	end
end

class Journey < ApplicationRecord
	validates_with JourneyUSValidator
	belongs_to :user
	validates :n_prenotati, presence: true
	validates :pay_method_id, presence: true
	validates :user_id, presence: true

	has_many :stages, inverse_of: :journey, dependent: :destroy
	has_many :routes, through: :stages
	has_many :notifications, as: :target, dependent: :destroy
	accepts_nested_attributes_for :stages

	# transazione che aggiorna il numero di passeggeri, crea l'associazione user-journey e
	# le associazioni journey-stages
	def booking
		self.transaction do
			for stage in self.stages do
				route = Route.find(stage.route_id)
				route.increment!(:n_passeggeri, by = self.n_prenotati)
			end
			self.save!
		end
	end

	# Cerca i journey che hanno uno stage relativo a una route di un dato guidatore
	# che devono essere accettati/rifiutati
	scope :find_requests, -> (driver_id) do
		includes("user","stages", "routes").where(stages: {accepted: nil} ,routes: {driver_id: driver_id})
	end


	# controlla se il viaggio è eliminabile secondo i vincoli temporali:
	# 48 ore o prima rispetto alla partenza;
	# sempre, se il guidatore ha modificato il viaggio entro 48 dalla partenza
	# 
	def self.journey_is_deletable(route)
		route.data_ora_partenza - 2.day > DateTime.current || route.data_ora_partenza - 2.day < route.updated_at
	end

	# controlla se entrambe i viaggi di un multitratta sono eliminabili secondo i vincoli temporali:
	# 48 ore o prima rispetto alla partenza;
	# sempre, se il guidatore ha modificato il viaggio entro 48 dalla partenza
	def self.journey_both_deletable(journey, id)
		unless journey.user_id == id
			false
		end
		route_1 = Route.find(journey.stages[0].route_id)
		route_2 = Route.find(journey.stages[1].route_id)
		(route_1.data_ora_partenza - 2.day > DateTime.current || route_1.data_ora_partenza - 2.day < route_1.updated_at) && (route_2.data_ora_partenza - 2.day > DateTime.current || route_2.data_ora_partenza - 2.day < route_2.updated_at)
	end


	# data una multitratta, cancella l'intera journey (quindi entrambi gli stages)

	def self.delete_journey(journey, routes)
		ActiveRecord::Base.transaction do
			routes.each do |r|
				r.decrement!(:n_passeggeri, by = journey.n_prenotati)
			end
			journey.destroy!
		end
	end

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :set_journey, only: [:destroy]


  # GET /journeys/new
  def new
    @routes = Route.find(params[:ids])
    @seats = []
    @journey = Journey.new

    # vengono cercati i posti disponibili per le route selezionate
    # e vengono creati gli stage
    @routes.each do |route|
      @seats   << route.posti_disponibili
      @journey.stages.build(route_id: route.id)
    end

    # vengono estratti tutti i metodi di pagamento dell'utente
    # utilizzabili per le route selezionate
    @pay_methods = Route.find_pay_method(current_user.id, @routes)
    @time = @routes.sum {|x| + x.tempo_percorrenza}
  end

  # POST /journey
  def create
    # creo un oggetto journey che contiene anche gli stages associati
    @journey = Journey.new(journey_params)
    respond_to do |format|
      if @journey.booking
        # la prenotazione ha avuto successo, crea le notifiche
        @journey.stages.each do |stage|
          Notification.create_notifications_td(stage.route.driver_id, current_user, stage.route, @journey, "reservation")
        end
        format.html { redirect_to user_bookings_path(current_user.id), notice: 'Prenotazione creata' }
        format.json { render :show, status: :created, location: @journey }
      else
        format.html { render :new }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  #GET /drivers/1/journeys
  def index
    # trova tutte le richieste che hanno accepted = nil
    @journeys = Journey.find_requests(current_user.driver_id)
  end

  #GET /routes/1/journeys/1/edit
  def edit
    @route = Route.find(params[:route_id])
    render template: 'errors/deleted_route' if @route.deleted?
    @journey =  Journey.find(params[:id])
    @user = @journey.user
    @checked = ! Stage.already_checked(@route.id,@journey.id).accepted.nil?
  end

  #PATCH /routes/1/journeys/1
  def update
    respond_to do |format|

      @route = Route.find(params[:route_id])
      @stage = @route.stages.where(journey_id: params[:id]).first
      @journey =  Journey.find(params[:id])

      if true?(params[:accept])
	if @stage.update(accepted: true)
          # crea la notifica una volta che la tratta è stata aggiornata correttamente
          Notification.create_notifications_th(@journey.user_id, current_user, @route, @route, "accept_trip")
          format.html { redirect_to root_path }
          format.json { render :show, status: :ok, location: @journey }
        else
          format.html { render :edit }
          format.json { render json: @journey.errors, status: :unprocessable_entity }
        end
      else
	if @stage.reject(@journey.n_prenotati)
          # crea la notifica una volta che la tratta è stata aggiornata correttamente
          Notification.create_notifications_th(@journey.user_id, current_user, @route, @route, "reject_trip")
          format.html { redirect_to root_path }
          format.json { render :show, status: :ok, location: @journey }
        else
          format.html { render :edit }
          format.json { render json: @journey.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  def manage_booking_delete
    @deleted_route =Route.find(params[:target])
    @other_route = Route.find(params[:other])
    if @other_route.deleted.eql?('true') #se l'altra route è stata eliminata prima della lettura di questa notifica
      @both_deleted = true
    else
      @both_deleted = false
      @other_stage = Stage.where("route_id = ?",@other_route.id).first #se non lo trova è perchè entrambe sono state cancellate -> DA GESTIRE
    end
    @first=Route.first_route(@other_route,@deleted_route)
  end

  def manage_booking_update
    @updated_route =Route.find(params[:target])
    @other_route = Route.find(params[:other])
    @posti_updated = @updated_route.posti_disponibili
    @posti_other = @other_route.posti_disponibili
    if (@first=Route.first_route(@other_route,@updated_route))
      @overlying = Route.overlying(@other_route,@updated_route)
    else
      @overlying = Route.overlying(@updated_route,@other_route)
    end
    @updated_stage = Stage.where("route_id = ?",@updated_route.id).first
    @other_stage = Stage.where("route_id = ?",@other_route.id).first
    @journey_id = @other_stage.journey_id
  end

  # DELETE /journeys/1
  #def destroy_temp
  #  route = Route.find(params[:r_id])
  #  is_deletable = Journey.journey_is_deletable(route)
  #  respond_to do |format|
  #    if current_user.id == @journey.user_id && is_deletable && Stage.delete_stage(@journey, route)
  #      Notification.create_notifications_td(route.driver_id, current_user, route, route, "cancel")
  #      format.html { redirect_to user_bookings_path(current_user.id), notice: 'Prenotazione eliminata' }
  #      format.json { head :no_content }
  #    else
  #      format.html { redirect_to detail_routes_path(multitrip: false, id: params[:r_id], j_id: params[:id]), notice: 'Errore eliminazione, non puoi annullare un viaggio se mancano meno di 48 ore alla partenza' }
  #      format.json { head :no_content }
  #    end
  #  end
  #end

  # DELETE /journeys/1
  # elimina entrambe gli stage
  def destroy
    route = []
    @journey.stages.sort_by { |x | x.route.data_ora_partenza  }.each do |stage|
      route << stage.route
    end
    both_deletable = Journey.journey_both_deletable(@journey, current_user.id)
    notification = params[:notification]
    respond_to do |format|
      if both_deletable && Journey.delete_journey(@journey, route)
        route.each do |r|
          Notification.create_notifications_td(r.driver_id, current_user, r, r, "cancel")
        end
        if notification
          format.html { redirect_to new_search_path(c_part: route.first.citta_partenza, c_arr: route.last.citta_arrivo, data_ora: route.first.data_ora_partenza) }
          format.json { head :no_content }
        else
          format.html { redirect_to user_bookings_path(current_user.id), notice: 'Entrambe i viaggi della multitratta sono stati eliminati' }
          format.json { head :no_content }
        end
      else
        format.html { redirect_to user_detail_booking_path(j_id:@journey.id), notice: 'Errore eliminazione, non puoi annullare un viaggio se mancano meno di 48 ore alla partenza' }
        format.json { head :no_content }
      end
    end
  end

  private
  def set_journey
    @journey = Journey.find(params[:id])
  end

  def get_driver_journey
    @driver = Driver.find(current_user.driver_id)
  end

  def journey_params
    params.require(:journey).permit(:user_id, :n_prenotati, :pay_method_id, stages_attributes: [:id, :route_id, :journey_id, :accepted])
  end

  def true?(obj)
    obj.to_s.downcase == "true"
  end
end

app/views/journeys/_form.html.erb
<%= form_with(model: journey, html: {class: "row col-12 col-12-mobilep"}, local: true) do |f| %>
  <% if journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journey.errors.count, "error") %> prohibited this passenger_association from being saved:</h2>

      <ul>
        <% journey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="action col-12 col-12-narrower"><hr></div>
  <div class="col-4 col-12-narrower">
	  <strong>Numero passeggeri</strong> 
    <%= f.number_field(:n_prenotati, in: 1.. @seats.max(), placeholder: "Numero Passeggeri") %>
    <br/>
  </div>
  <div class="col-4 col-12-narrow">
    <strong>Metodo di pagamento</strong>
    <%= f.collection_select :pay_method_id, @pay_methods, :id, :numero, {}, {required: true}%>
    <br/>
  </div>
  <div class="action col-12 col-12-narrow">
	  <label><br/></label>
    <%= link_to 'Aggiungi metodo di pagamento',new_user_pay_method_path(user_id: current_user), class: 'button'%>
    <script src="app/assets/js/route.js">  </script>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id%>

  <%= f.fields_for :stages do |f_stage| %>
    <%= f_stage.hidden_field :route_id %>
    <%= f_stage.hidden_field :journey_id %>
  <% end %>
  <div><br></div>
  <div class=" action col-12 col-12-narrow">
    <%= f.submit "Prenota"%>
  </div>
<% end %>

app/views/journeys/edit.html.erb
<% if @checked %>
  <div class="col-12 col-12-narrower">
  <h2> Ops!</h2>
  </div>
  <div class="col-12 col-12-narrower">
  <h3>Sembra che tu abbia già controllato questa richiesta!</h3>
  </div>

<%else %>
<!--Dati dell'autostoppista-->
<div class="row gtr-uniform">
  <h4 class="image col-12 col-12-narrower">
    <%if @user.avatar.url == nil%>
      <%= image_tag 'images/default.jpeg' , size: "160"%>
    <%else %>
      <%=image_tag(@user.avatar.url, size: "160") %>
    <%end %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Nome:</strong>
    <%= @user.nome %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Cognome:</strong>
    <%= @user.cognome %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Username:</strong>
    <%= @user.username %>
  </h4>
  <h4 class="col-4 col-12-narrower">
    <strong>Email:</strong>
    <%= @user.email %>
  </h4>
  <div class="col-6 col-12-narrower">
    <h4><strong>Rating medio autostoppista</strong></h4>
    <%if @user.hitch_hiker_rating==nil %>
      Nessuna valutazione presente!
    <%else %>
      <%=@user.hitch_hiker_rating.round(2)%>
    <%end %>
  </div>
</div>
<div class="col-12 col-12-mobilep"><br></div>
<div class="col-12 col-12-mobilep"><br></div>
<div class="row gtr-uniform">
  <div class="col-12 col-12-mobilep" style="overflow: auto;">
    <table>
      <caption><h3><strong>Tratta richiesta</strong></h3></caption>
      <thead>
      <tr>
        <th>Città di Partenza</th>
        <th>Luogo di ritrovo</th>
        <th>Data e ora partenza</th>
        <th>Città di arrivo</th>
      </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @route.citta_partenza %></td>
            <td><%= @route.luogo_ritrovo %></td>
            <td><%= @route.data_ora_partenza.strftime("%d/%m/%y, %H:%M") %></td>
            <td><%= @route.citta_arrivo %></td>

            <td><%= link_to 'Dettagli', driver_route_path(current_user.driver_id, @route.id), class: "button" %></td>
          </tr>
        <tr>
          <td colspan="8"></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-12 col-12-mobilep"><br></div>
</div>
<div class="row gtr-uniform">
  <div class="col-12 col-12-mobile">

  <%= link_to 'Accetta', route_journey_path(@route, @journey, :accept => "true" ), method: :patch, class: "button", title: 'Accetta' %>
  <%= link_to 'Rifiuta', route_journey_path(@route, @journey, :accept => "false"), method: :patch, class: "button", title: 'Rifiuta'%>

  </div>
</div>
  <%end %>

<!--
<render 'form', passenger_association: @passenger_association %>

< link_to 'Show', @passenger_association %> |
< link_to 'Back', passenger_associations_path %>
-->

app/views/journeys/index.html.erb
<div class="row gtr-uniform">
  <div class="col-12 col-12-mobile">
    <h2><strong>Richieste di prenotazione</strong></h2>
  </div>
  <% @journeys.each do |journey| %>
    <% journey.stages.each do |stage| %>
      <div class="col-12 col-12-mobile">
        <%= journey.user.username%> vorrebbe percorrere la tua tratta ! &nbsp;<%=link_to 'Vedi dettagli', edit_route_journey_path(stage.route, journey), class: "button"%>
      </div>
    <% end %>
  <% end %>
</div>
<br>

app/views/journeys/manage_booking_delete.html.erb
<%if !@both_deleted %>

  <div class="col-12 col-12-mobile">
    <h3>Oh no..</h3>
    <h1><a>Sembra che la tratta </a><%= @deleted_route.citta_partenza%>-<%= @deleted_route.citta_arrivo%><a> sia stata cancellata dal conducente :(</a></h1>
    <h1>Preferisci cercare una nuova tratta che sostituisca quella che è stata cancellata o vuoi disdire la prenotazione dell'altra tratta per cercare un viaggio ex novo?</h1>
  </div>

  <div class="col-12 col-12-mobile">
    <%= link_to 'Completa viaggio esistente', new_search_path(c_part: @deleted_route.citta_partenza, c_arr: @deleted_route.citta_arrivo, data_ora: @deleted_route.data_ora_partenza),class: "button special" ,title: 'Completa il viaggio'%>
    <% if @first %>
      <%= link_to 'Cerca nuovo viaggio', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @other_route.citta_partenza,c_arr: @deleted_route.citta_arrivo,data: @other_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione già accettata e cercare un nuovo viaggio?' }, class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <% else %>
      <%= link_to 'Cerca nuovo viaggio', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @deleted_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @deleted_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione già accettata e cercare un nuovo viaggio?' }, class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <%end %>
  </div>

<%else %>

  <div class="col-12 col-12-mobile">
    <h3>Oh no..</h3>
    <h1><a>Sembra che entrambe le tratte che componevano il viaggio </a><%= @deleted_route.citta_partenza%>-<%= @other_route.citta_arrivo%><a> siano state cancellate dai conducenti :(</a></h1>
    <h1>Non ti preoccupare! Cerca subito un nuovo viaggio che ti porti a destinazione!</h1>
  </div>

  <div class="col-12 col-12-mobile">
    <% if @first %>
      <%= link_to 'Cerca nuovo viaggio', new_search_path(c_part: @other_route.citta_partenza,c_arr: @deleted_route.citta_arrivo,data: @other_route.data_ora_partenza), class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <% else %>
      <%= link_to 'Cerca nuovo viaggio', new_search_path(c_part: @deleted_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @deleted_route.data_ora_partenza), class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <%end %>
  </div>

<%end %>

app/views/journeys/manage_booking_update.html.erb
<% if !@overlying %>
  <div class="col-12 col-12-mobile">
    <h2><strong>Attenzione!</strong></h2>
    <h1>Sembra che il tuo viaggio abbia subito una modifica da parte dei guidatori. </h1>
    <h1>Ecco i dettagli aggiornati: </h1>
  </div>

    <% if @first %>
      <div class="col-6 col-12-mobilep">
        <h1><strong>Prima tratta</strong></h1>
        <%= render 'routes/detail_route', route: @other_route, posti: @posti_other %>
      </div>
      <div class="col-6 col-12-mobilep">
        <h1><strong>Seconda tratta</strong></h1>
        <%= render 'routes/detail_route', route: @updated_route, posti: @posti_updated %>
      </div>
    <% else %>
      <div class="col-6 col-12-mobilep">
        <h3><strong>Prima tratta</strong></h3>
        <%= render 'routes/detail_route', route: @updated_route, posti: @posti_updated %>
      </div>
      <div class="col-6 col-12-mobilep">
        <h3><strong>Seconda tratta</strong></h3>
        <%= render 'routes/detail_route', route: @other_route, posti: @posti_other %>
      </div>
    <% end %>

  <div class="col-12 col-12-mobilep">
    <h1>Se le modifiche non sono di tuo gradimento, puoi decidere di cancellare una delle due tratte per cercarne una sostitutiva che soddisfi le tue esigenze.</h1>
  </div>

  <div>
    <% if @first %>
      <%= link_to 'Sostituisci la prima tratta', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @other_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @other_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la prima tratta' %>
      <%= link_to 'Sostituisci la seconda tratta', stage_path(j_id: @updated_stage.journey_id, r_id: @updated_route.id, c_part: @updated_route.citta_partenza,c_arr: @updated_route.citta_arrivo,data: @updated_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la seconda tratta' %>
    <% else %>
      <%= link_to 'Sostituisci la prima tratta', stage_path(j_id: @updated_stage.journey_id, r_id: @updated_route.id, c_part: @updated_route.citta_partenza,c_arr: @updated_route.citta_arrivo,data: @updated_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la prima tratta' %>
      <%= link_to 'Sostituisci la seconda tratta', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @other_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @other_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la seconda tratta' %>
    <% end %>
    <%= link_to 'Accetta le modifiche', user_bookings_path(current_user), class: "button special" ,title: 'Accetta le modifiche' %>
  </div>

<%else %>
  <div class="col-12 col-12-mobile">
    <h2><strong>Attenzione!</strong></h2>
    <h1>Sembra che il tuo viaggio abbia subito una modifica da parte dei guidatori e ora <strong>il cambio tra le tratte non è più possibile.</strong></h1>
    <h1>Ecco i dettagli aggiornati: </h1>
  </div>

  <% if @first %>
    <div class="col-6 col-12-mobilep">
      <h1><strong>Prima tratta</strong></h1>
      <%= render 'routes/detail_route', route: @other_route, posti: @posti_other %>
    </div>
    <div class="col-6 col-12-mobilep">
      <h1><strong>Seconda tratta</strong></h1>
      <%= render 'routes/detail_route', route: @updated_route, posti: @posti_updated %>
    </div>
  <% else %>
    <div class="col-6 col-12-mobilep">
      <h1><strong>Prima tratta</strong></h1>
      <%= render 'routes/detail_route', route: @updated_route, posti: @posti_updated %>
    </div>
    <div class="col-6 col-12-mobilep">
      <h1><strong>Seconda tratta</strong></h1>
      <%= render 'routes/detail_route', route: @other_route, posti: @posti_other %>
    </div>
  <% end %>

  <div>
    <h1>Puoi decidere di cancellare una delle due tratte per cercarne una sostitutiva che ti permetta di effettuare il cambio oppure puoi annullare entrambe le prenotazioni e cercare un viaggio ex novo.</h1>
  </div>

  <div>
    <% if @first %>
      <%= link_to 'Sostituisci la prima tratta', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @other_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @other_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la prima tratta' %>
      <%= link_to 'Sostituisci la seconda tratta', stage_path(j_id: @updated_stage.journey_id, r_id: @updated_route.id, c_part: @updated_route.citta_partenza,c_arr: @updated_route.citta_arrivo,data: @updated_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la seconda tratta' %>
      <%= link_to 'Cerca un nuovo viaggio', journey_path(j_id: @journey_id, notification: true),class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <% else %>
      <%= link_to 'Sostituisci la prima tratta', stage_path(j_id: @updated_stage.journey_id, r_id: @updated_route.id, c_part: @updated_route.citta_partenza,c_arr: @updated_route.citta_arrivo,data: @updated_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la prima tratta' %>
      <%= link_to 'Sostituisci la seconda tratta', stage_path(j_id: @other_stage.journey_id, r_id: @other_route.id, c_part: @other_route.citta_partenza,c_arr: @other_route.citta_arrivo,data: @other_route.data_ora_partenza),  method: :delete, data: { confirm: 'Sicuro di voler annullare la prenotazione e cercare una tratta sostitutiva?' }, class: "button special" ,title: 'Sostituisci la seconda tratta' %>
      <%= link_to 'Cerca un nuovo viaggio', journey_path(id: @journey_id, notification: true),method: :delete, data: { confirm: 'Sicuro di voler annullare entrambe le prenotazioni e cercare un viaggio ex novo?' }, class: "button special" ,title: 'Cerca nuovo viaggio' %>
    <% end %>
  </div>

<%end %>

app/views/journeys/new.html.erb
<div class="col-10 col-8-mobilep">
  <h2><strong>Prenota il viaggio</strong></h2>
</div>
  
<div class="col-10 col-8-mobilep">
 <% @routes.each do |route| %>
  <div class="col-12 col-12-mobilep">
	  <h3><strong><%= route.citta_partenza %> - <%= route.citta_arrivo%> </strong></h3> 
	  <h4> partenza <%= route.data_ora_partenza.strftime("il %d-%m-%Y alle %H:%M:%S") %>, arrivo <%= route.data_ora_arrivo.strftime("il %d-%m-%Y alle %H:%M:%S")%> </h4>
  </div>

  
 <%end %>
 <div class="col-12 col-12-mobilep">
	  <strong> Durata totale: <%= @time/60 %> ore <%=@time%60%> minuti </strong>
	  <p></p>
	  <strong> Costo totale a persona: <%= @routes.sum {|x| + x.costo}%> </strong>
 </div>
</div>

<br>

<%= render 'form', journey: @journey %>

<div class="action col-12 col-12-narrower"><hr></div>
<div class="action col-12 col-12-narrower">
  <%= link_to 'Indietro', :back, class: "button special"%>
</div>

app/views/journeys/show.html.erb
<%= link_to 'Edit', edit_passenger_association_path(@passenger_association) %> |
<%= link_to 'Back', passenger_associations_path %>